/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LanguageImport } from './routes/$language'
import { Route as IndexImport } from './routes/index'
import { Route as LanguageIndexImport } from './routes/$language/index'
import { Route as LanguageSavedImport } from './routes/$language/saved'
import { Route as LanguageResourcesIdImport } from './routes/$language/resources/$id'

// Create/Update Routes

const LanguageRoute = LanguageImport.update({
  path: '/$language',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LanguageIndexRoute = LanguageIndexImport.update({
  path: '/',
  getParentRoute: () => LanguageRoute,
} as any)

const LanguageSavedRoute = LanguageSavedImport.update({
  path: '/saved',
  getParentRoute: () => LanguageRoute,
} as any)

const LanguageResourcesIdRoute = LanguageResourcesIdImport.update({
  path: '/resources/$id',
  getParentRoute: () => LanguageRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$language': {
      id: '/$language'
      path: '/$language'
      fullPath: '/$language'
      preLoaderRoute: typeof LanguageImport
      parentRoute: typeof rootRoute
    }
    '/$language/saved': {
      id: '/$language/saved'
      path: '/saved'
      fullPath: '/$language/saved'
      preLoaderRoute: typeof LanguageSavedImport
      parentRoute: typeof LanguageImport
    }
    '/$language/': {
      id: '/$language/'
      path: '/'
      fullPath: '/$language/'
      preLoaderRoute: typeof LanguageIndexImport
      parentRoute: typeof LanguageImport
    }
    '/$language/resources/$id': {
      id: '/$language/resources/$id'
      path: '/resources/$id'
      fullPath: '/$language/resources/$id'
      preLoaderRoute: typeof LanguageResourcesIdImport
      parentRoute: typeof LanguageImport
    }
  }
}

// Create and export the route tree

interface LanguageRouteChildren {
  LanguageSavedRoute: typeof LanguageSavedRoute
  LanguageIndexRoute: typeof LanguageIndexRoute
  LanguageResourcesIdRoute: typeof LanguageResourcesIdRoute
}

const LanguageRouteChildren: LanguageRouteChildren = {
  LanguageSavedRoute: LanguageSavedRoute,
  LanguageIndexRoute: LanguageIndexRoute,
  LanguageResourcesIdRoute: LanguageResourcesIdRoute,
}

const LanguageRouteWithChildren = LanguageRoute._addFileChildren(
  LanguageRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$language': typeof LanguageRouteWithChildren
  '/$language/saved': typeof LanguageSavedRoute
  '/$language/': typeof LanguageIndexRoute
  '/$language/resources/$id': typeof LanguageResourcesIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$language/saved': typeof LanguageSavedRoute
  '/$language': typeof LanguageIndexRoute
  '/$language/resources/$id': typeof LanguageResourcesIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$language': typeof LanguageRouteWithChildren
  '/$language/saved': typeof LanguageSavedRoute
  '/$language/': typeof LanguageIndexRoute
  '/$language/resources/$id': typeof LanguageResourcesIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$language'
    | '/$language/saved'
    | '/$language/'
    | '/$language/resources/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$language/saved' | '/$language' | '/$language/resources/$id'
  id:
    | '__root__'
    | '/'
    | '/$language'
    | '/$language/saved'
    | '/$language/'
    | '/$language/resources/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LanguageRoute: typeof LanguageRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LanguageRoute: LanguageRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$language"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$language": {
      "filePath": "$language.tsx",
      "children": [
        "/$language/saved",
        "/$language/",
        "/$language/resources/$id"
      ]
    },
    "/$language/saved": {
      "filePath": "$language/saved.tsx",
      "parent": "/$language"
    },
    "/$language/": {
      "filePath": "$language/index.tsx",
      "parent": "/$language"
    },
    "/$language/resources/$id": {
      "filePath": "$language/resources/$id.tsx",
      "parent": "/$language"
    }
  }
}
ROUTE_MANIFEST_END */
